#pragma once

#include <tabletop/input_recorder.h>

#include <giocamo/online/online.h>

struct Menu_Result {
  enum Mode { VS_AI, ONLINE } mode = VS_AI;
  // Seat this peer plays. Always 0 for solo play; matchmaker-assigned for
  // online (where the two peers get different indices).
  int player_index = 0;
  // Deal seed. In online mode it's the matchmaker's seed (both peers share
  // it); in solo it's whatever the CLI passed or a random one generated by
  // parse_play_args(). Always a real value — quick_setup() can be called
  // with it directly.
  int seed = 0;
  // Valid only when mode == ONLINE.
  Online online;

  bool is_online() const { return mode == ONLINE; }
};

// Opens a raylib window for the menu and returns the user's choice.
// The window stays open after this returns so main can render the game inside
// it. `recorder` drives the menu's per-frame input — Live captures from raylib,
// Record also stores frames, Playback replays them.
Menu_Result run_menu(
  const std::string& title, Vector2 window_size, Input_Feed& recorder
);
